version: "3.8"
services:
  sunrise:
    build:
      context: .
    container_name: sunrise
    image: sunrise
    ports:
      - "3000:3000"
    volumes:
      - ./sunrise/:/app
      - /app/node_modules
    tty: true
    stdin_open: true
